// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Theo_DisableTouchUI","status":true,"description":"Removes the touch UI and reposition the menu accordingly","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"MZPlusQuickStart","status":true,"description":"<MZPlusQuickStart> Skips the title for fast testing. (Will only skip the title in dev mode).  Credit to Quasi.","parameters":{"Dev Mode Only":"false"}},
{"name":"Center_ShowChoices","status":true,"description":"Centers or offsets the Show Choices window position","parameters":{"Offset X":"0","Offset Y":"0"}},
{"name":"SaveFunctionOverride","status":true,"description":"Adds a \"Save Manager\" section with Save, Load, and Delete tabs to the main menu.","parameters":{}},
{"name":"AltSaveScreen2","status":true,"description":"Alternative save/load screen layout – file list only.","parameters":{}},
{"name":"Invisible_Pointer","status":true,"description":"v1.0.0 - With this plugin you can change the destination place sprite of the mouse\\touch input.\r\n<DestinationSprite>","parameters":{"Sprite Figure":"Square","Custom Image":"image","Animation mode":"Blink","Fade speed":"12","Sprite Size":"48","Sprite Color":"#ffffff","Sprite Opacity":"0","Sprite Blend":"1"}}
];
